### PR TITLE
Ensure only a single task is created

### PR DESCRIPTION
**Pull request by rozza**
KAFKA-62

### CODE REVIEW

**Review by jyemin — COMMENTED** [review]
Can you give me some background to help understand this change?  What is going wrong now and how does this fix it?

**Comment by rozza** [comment]
This ensures no matter what the user configures only a single task configuration is created.  Stopping users accidentally misconfiguring and duplicating processing or messages to/from topics.

https://evergreen.mongodb.com/version/5ddd3cde56234319b545bb2b

**Comment by jyemin** [comment]
Ah, I see.  What's the default value for maxTasks?  If it's 1, then would it be better to instead throw an exception when maxTasks > 1 rather than ignore the user's configuration?  

I don't have an opinion on it, just throwing it out there as an alternative.

**Comment by rozza** [comment]
Its not ignoring it as such - its just the maximum number the connector is allowed produce. This is for connectors that can handle different levels of parallelism.

**Review by jyemin — APPROVED** [review]
LGTM

**Pull request closed without merging**
