### PR TITLE
Fix confluent archive format

### PR DESCRIPTION
**Pull request by rozza**
KAFKA-41

### CODE REVIEW

**Comment by rozza** [comment]
less build/confluent/monogdb-kafka-connect-mongodb-0.2-SNAPSHOT.zip
```
Archive:  build/confluent/monogdb-kafka-connect-mongodb-0.2-SNAPSHOT.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
       0  Defl:N        2   0% 2019-07-18 13:39 00000000  monogdb-kafka-connect-mongodb-0.2-SNAPSHOT/
       0  Defl:N        2   0% 2019-07-18 13:39 00000000  monogdb-kafka-connect-mongodb-0.2-SNAPSHOT/etc/
    1388  Defl:N      585  58% 2019-07-18 13:39 aa24fe71  monogdb-kafka-connect-mongodb-0.2-SNAPSHOT/etc/MongoSinkConnector.properties
     394  Defl:N      242  39% 2019-07-18 13:39 4016eb12  monogdb-kafka-connect-mongodb-0.2-SNAPSHOT/etc/MongoSourceConnector.properties
       0  Defl:N        2   0% 2019-07-18 13:39 00000000  monogdb-kafka-connect-mongodb-0.2-SNAPSHOT/lib/
 2108444  Defl:N  1896885  10% 2019-07-18 13:39 c919fa65  monogdb-kafka-connect-mongodb-0.2-SNAPSHOT/lib/mongo-kafka-0.2-SNAPSHOT-all.jar
       0  Defl:N        2   0% 2019-07-18 13:39 00000000  monogdb-kafka-connect-mongodb-0.2-SNAPSHOT/assets/
    6877  Defl:N     6747   2% 2019-07-18 13:39 af9a59d7  monogdb-kafka-connect-mongodb-0.2-SNAPSHOT/assets/mongodb-leaf.png
   80287  Defl:N    60927  24% 2019-07-18 13:39 4e3375b3  monogdb-kafka-connect-mongodb-0.2-SNAPSHOT/assets/mongodb-logo.png
       0  Defl:N        2   0% 2019-07-18 13:39 00000000  monogdb-kafka-connect-mongodb-0.2-SNAPSHOT/doc/
    3204  Defl:N     1506  53% 2019-07-18 13:39 cac4055e  monogdb-kafka-connect-mongodb-0.2-SNAPSHOT/doc/README.md
   11373  Defl:N     3968  65% 2019-07-18 13:39 f8c49223  monogdb-kafka-connect-mongodb-0.2-SNAPSHOT/doc/LICENSE.txt
    1401  Defl:N      626  55% 2019-07-18 13:39 704b42ff  monogdb-kafka-connect-mongodb-0.2-SNAPSHOT/manifest.json
```

**Comment by llamadew** [comment]
monogdb?

**Comment by llamadew** [comment]
and, can the name be dynamically generated from project properties?

**Comment by llamadew** [comment]
and, can the name be dynamically generated from project properties?

**Review by llamadew — APPROVED** [review]
Works locally!

**Pull request closed without merging**
